#!/usr/bin/env python3
"""Publish API drift results as admin-only feedback messages."""

from __future__ import annotations

import argparse
import json
import os
import sys
from dataclasses import dataclass
from datetime import datetime, timezone
from hashlib import sha256
from pathlib import Path
from typing import Any
from urllib import error, parse, request
from zoneinfo import ZoneInfo


SYSTEM_PREFIX = "[SYSTEM][API-DRIFT]"
MAX_FEEDBACK_MESSAGE_LENGTH = 1000


class AlertMessageError(RuntimeError):
	"""Raised when publishing admin-only API drift messages cannot proceed."""


@dataclass(frozen=True)
class Config:
	api_base_url: str
	admin_user: str
	admin_password: str
	api_token: str | None
	timeout_seconds: float


@dataclass(frozen=True)
class AlertDecision:
	needed: bool
	highest_risk: str
	threshold: str
	fingerprint: str


def parse_args() -> argparse.Namespace:
	parser = argparse.ArgumentParser(
		description="Publish API drift status into admin-only feedback messages.",
	)
	parser.add_argument(
		"--env-file",
		default=".env.codex-feedback-automation.local",
		help="Env file that contains feedback admin credentials.",
	)
	parser.add_argument(
		"--latest-json",
		default=".codex/api-drift/latest.json",
		help="Latest drift result JSON generated by check_api_drift.py.",
	)
	parser.add_argument(
		"--message-state-file",
		default=".codex/api-drift/message-state.json",
		help="State file for dedupe and traceability.",
	)
	parser.add_argument(
		"--threshold",
		default="",
		help="Alert threshold: none|medium|high. Empty means read from env/API_DRIFT_ALERT_THRESHOLD.",
	)
	parser.add_argument(
		"--timezone",
		default="Asia/Shanghai",
		help="Timezone used in message rendering and dedupe day key.",
	)
	parser.add_argument(
		"--max-target-details",
		type=int,
		default=5,
		help="Maximum number of risk targets rendered in message details.",
	)
	parser.add_argument(
		"--timeout-seconds",
		type=float,
		default=20.0,
		help="HTTP timeout for each API call.",
	)
	parser.add_argument(
		"--force",
		action="store_true",
		help="Force publish even when dedupe key is unchanged.",
	)
	parser.add_argument(
		"--keep-previous-system-messages",
		action="store_true",
		help="Keep previous unresolved system messages instead of auto-closing them.",
	)
	parser.add_argument(
		"--dry-run",
		action="store_true",
		help="Only print payload and decision without sending to API.",
	)
	return parser.parse_args()


def load_env_file(path: Path) -> dict[str, str]:
	env: dict[str, str] = {}
	if not path.exists():
		return env
	for raw_line in path.read_text(encoding="utf-8").splitlines():
		line = raw_line.strip()
		if not line or line.startswith("#") or "=" not in line:
			continue
		key, value = line.split("=", 1)
		env[key.strip()] = value.strip().strip("'").strip('"')
	return env


def require_env(env: dict[str, str], name: str) -> str:
	value = env.get(name, "").strip()
	if not value:
		raise AlertMessageError(f"Missing required environment variable: {name}")
	return value


def build_config(env: dict[str, str], timeout_seconds: float) -> Config:
	return Config(
		api_base_url=require_env(env, "FEEDBACK_API_BASE_URL").rstrip("/"),
		admin_user=require_env(env, "FEEDBACK_ADMIN_USER"),
		admin_password=require_env(env, "FEEDBACK_ADMIN_PASSWORD"),
		api_token=env.get("FEEDBACK_API_TOKEN", "").strip() or None,
		timeout_seconds=timeout_seconds,
	)


def normalize_threshold(value: str) -> str:
	candidate = value.strip().lower()
	if candidate in {"none", "medium", "high"}:
		return candidate
	return "high"


def risk_rank(value: str) -> int:
	if value == "high":
		return 2
	if value == "medium":
		return 1
	return 0


def load_json(path: Path) -> Any:
	if not path.exists():
		raise AlertMessageError(f"File not found: {path}")
	try:
		return json.loads(path.read_text(encoding="utf-8"))
	except json.JSONDecodeError as exc:
		raise AlertMessageError(f"Invalid JSON file: {path}") from exc


def ensure_parent(path: Path) -> None:
	path.parent.mkdir(parents=True, exist_ok=True)


def build_stable_fingerprint(results: list[dict[str, Any]], threshold: str) -> str:
	normalized = [
		{
			"id": str(item.get("id", "")),
			"risk_level": str(item.get("risk_level", "none")).strip().lower(),
			"risk_reason": str(item.get("risk_reason", "") or ""),
			"missing_paths": item.get("missing_paths", []),
			"added_paths": item.get("added_paths", []),
		}
		for item in sorted(results, key=lambda entry: str(entry.get("id", "")))
		if risk_rank(str(item.get("risk_level", "none")).strip().lower()) >= risk_rank(threshold)
	]
	return sha256(json.dumps(normalized, ensure_ascii=False, sort_keys=True).encode("utf-8")).hexdigest()


def extract_alert_decision(latest_payload: dict[str, Any], threshold: str) -> AlertDecision:
	alert_payload = latest_payload.get("alert") if isinstance(latest_payload, dict) else None
	highest_risk = "none"
	fingerprint = ""
	if isinstance(alert_payload, dict):
		highest_risk = str(alert_payload.get("highest_risk", "none")).strip().lower()
		fingerprint = str(alert_payload.get("fingerprint", "")).strip()

	if highest_risk not in {"none", "medium", "high"}:
		highest_risk = "none"

	results = latest_payload.get("results", [])
	if not isinstance(results, list):
		results = []

	if not fingerprint:
		fingerprint = build_stable_fingerprint(
			[item for item in results if isinstance(item, dict)],
			threshold,
		)

	needed = risk_rank(highest_risk) >= risk_rank(threshold)
	return AlertDecision(
		needed=needed,
		highest_risk=highest_risk,
		threshold=threshold,
		fingerprint=fingerprint,
	)


def make_headers(config: Config) -> dict[str, str]:
	headers = {
		"Content-Type": "application/json",
		"User-Agent": "codex-api-drift-message-alert/1.0",
	}
	if config.api_token:
		headers["X-API-Key"] = config.api_token
	return headers


def api_request(
	opener: request.OpenerDirector,
	config: Config,
	method: str,
	path: str,
	payload: dict[str, Any] | None = None,
) -> Any:
	url = parse.urljoin(f"{config.api_base_url}/", path.lstrip("/"))
	body = json.dumps(payload, ensure_ascii=False).encode("utf-8") if payload is not None else None
	request_obj = request.Request(
		url=url,
		method=method,
		data=body,
		headers=make_headers(config),
	)
	try:
		with opener.open(request_obj, timeout=config.timeout_seconds) as response:
			raw = response.read().decode("utf-8")
	except error.HTTPError as exc:
		message = exc.read().decode("utf-8", errors="replace") if exc.fp else ""
		raise AlertMessageError(f"API {method} {path} failed: HTTP {exc.code} {message[:320]}") from exc
	except error.URLError as exc:
		raise AlertMessageError(f"API {method} {path} failed: {exc.reason}") from exc

	if not raw:
		return None
	try:
		return json.loads(raw)
	except json.JSONDecodeError as exc:
		raise AlertMessageError(f"API {method} {path} returned invalid JSON") from exc


def login_admin(opener: request.OpenerDirector, config: Config) -> None:
	try:
		api_request(
			opener,
			config,
			"POST",
			"/api/auth/login",
			{
				"user_id": config.admin_user,
				"password": config.admin_password,
			},
		)
	except AlertMessageError as exc:
		if config.api_token and "HTTP 405" in str(exc):
			return
		raise


def parse_run_at(run_at_text: str, tz_name: str) -> datetime:
	if not run_at_text:
		raise AlertMessageError("latest.json missing run_at timestamp")
	try:
		run_at = datetime.fromisoformat(run_at_text)
	except ValueError as exc:
		raise AlertMessageError(f"Invalid run_at timestamp: {run_at_text}") from exc
	if run_at.tzinfo is None:
		run_at = run_at.replace(tzinfo=timezone.utc)
	try:
		tz = ZoneInfo(tz_name)
	except Exception:
		tz = timezone.utc
	return run_at.astimezone(tz)


def choose_notice_kind(decision: AlertDecision) -> str:
	if decision.needed:
		return "alert"
	if decision.highest_risk != "none":
		return "drift-no-alert"
	return "healthy"


def build_notification_key(
	notice_day: str,
	notice_kind: str,
	decision: AlertDecision,
	summary: dict[str, Any],
) -> str:
	base = {
		"day": notice_day,
		"kind": notice_kind,
		"threshold": decision.threshold,
		"highest_risk": decision.highest_risk,
		"fingerprint": decision.fingerprint,
		"summary": {
			"high": int(summary.get("high", 0) or 0),
			"medium": int(summary.get("medium", 0) or 0),
			"none": int(summary.get("none", 0) or 0),
		},
	}
	return sha256(json.dumps(base, ensure_ascii=False, sort_keys=True).encode("utf-8")).hexdigest()


def format_target_line(target: dict[str, Any]) -> str:
	target_id = str(target.get("id", "unknown"))
	risk_reason = str(target.get("risk_reason", "unknown"))
	status_code = target.get("status_code")
	status_text = str(status_code) if status_code is not None else "n/a"
	return f"- {target_id} (http={status_text}, reason={risk_reason})"


def build_feedback_message(
	latest_payload: dict[str, Any],
	decision: AlertDecision,
	notice_kind: str,
	run_at_local: datetime,
	max_target_details: int,
) -> str:
	summary = latest_payload.get("summary") if isinstance(latest_payload, dict) else {}
	results = latest_payload.get("results") if isinstance(latest_payload, dict) else []
	report_path = str(latest_payload.get("report_path", ""))

	risk_targets: list[dict[str, Any]] = []
	if isinstance(results, list):
		for item in results:
			if not isinstance(item, dict):
				continue
			risk_level = str(item.get("risk_level", "none")).strip().lower()
			if risk_level in {"high", "medium"}:
				risk_targets.append(item)

	kind_text_map = {
		"alert": "报警",
		"drift-no-alert": "有变化（未达报警阈值）",
		"healthy": "无变化",
	}
	kind_text = kind_text_map.get(notice_kind, "状态通知")

	lines: list[str] = []
	lines.append(f"{SYSTEM_PREFIX} {run_at_local:%Y-%m-%d} {kind_text}")
	lines.append(f"巡检时间：{run_at_local:%Y-%m-%d %H:%M:%S %Z}")
	lines.append(f"风险等级：{decision.highest_risk}（阈值 {decision.threshold}）")
	lines.append(
		"摘要："
		f"high={int(summary.get('high', 0) or 0)} / "
		f"medium={int(summary.get('medium', 0) or 0)} / "
		f"none={int(summary.get('none', 0) or 0)}"
	)
	if report_path:
		lines.append(f"报告：{report_path}")
	if risk_targets:
		lines.append("风险目标：")
		for target in risk_targets[: max(1, max_target_details)]:
			lines.append(format_target_line(target))
	lines.append("说明：本通知仅写入 admin 消息，不会推送给普通用户。")

	message = "\n".join(lines)
	if len(message) <= MAX_FEEDBACK_MESSAGE_LENGTH:
		return message
	truncated = message[: MAX_FEEDBACK_MESSAGE_LENGTH - 20].rstrip()
	return f"{truncated}\n...[truncated]"


def load_message_state(path: Path) -> dict[str, Any]:
	if not path.exists():
		return {}
	try:
		payload = json.loads(path.read_text(encoding="utf-8"))
	except json.JSONDecodeError:
		return {}
	return payload if isinstance(payload, dict) else {}


def save_message_state(path: Path, state: dict[str, Any]) -> None:
	ensure_parent(path)
	path.write_text(json.dumps(state, ensure_ascii=False, indent=2), encoding="utf-8")


def resolve_feedback_classification(
	notice_kind: str,
	highest_risk: str,
) -> tuple[str, str, str]:
	if notice_kind == "alert":
		if highest_risk == "high":
			return ("SYSTEM_ALERT", "HIGH", "API_MONITOR")
		return ("SYSTEM_ALERT", "MEDIUM", "API_MONITOR")
	if notice_kind == "drift-no-alert":
		return ("SYSTEM_TASK", "MEDIUM", "API_MONITOR")
	return ("SYSTEM_HEARTBEAT", "LOW", "API_MONITOR")


def create_admin_feedback(
	opener: request.OpenerDirector,
	config: Config,
	message: str,
	category: str,
	priority: str,
	source: str,
) -> dict[str, Any]:
	response = api_request(
		opener,
		config,
		"POST",
		"/api/feedback",
		{
			"message": message,
			"category": category,
			"priority": priority,
			"source": source,
		},
	)
	if not isinstance(response, dict):
		raise AlertMessageError("Create admin feedback returned unexpected response")
	return response


def list_feedback_for_admin(
	opener: request.OpenerDirector,
	config: Config,
) -> list[dict[str, Any]]:
	response = api_request(opener, config, "GET", "/api/admin/feedback")
	if not isinstance(response, list):
		return []
	return [item for item in response if isinstance(item, dict)]


def close_feedback_item(
	opener: request.OpenerDirector,
	config: Config,
	feedback_id: int,
) -> None:
	api_request(
		opener,
		config,
		"POST",
		f"/api/admin/feedback/{feedback_id}/close",
	)


def close_previous_system_messages(
	opener: request.OpenerDirector,
	config: Config,
	new_feedback_id: int,
) -> list[int]:
	closed_ids: list[int] = []
	items = list_feedback_for_admin(opener, config)
	for item in items:
		feedback_id = int(item.get("id") or 0)
		if feedback_id <= 0 or feedback_id == new_feedback_id:
			continue
		message = str(item.get("message", ""))
		category = str(item.get("category", ""))
		is_system = bool(item.get("is_system"))
		resolved_at = item.get("resolved_at")
		if not (is_system or category.startswith("SYSTEM_") or message.startswith(SYSTEM_PREFIX)):
			continue
		if resolved_at is not None:
			continue
		close_feedback_item(opener, config, feedback_id)
		closed_ids.append(feedback_id)
	return closed_ids


def main() -> int:
	args = parse_args()
	env = dict(os.environ)
	env.update(load_env_file(Path(args.env_file)))

	threshold_input = args.threshold.strip() if args.threshold.strip() else env.get(
		"API_DRIFT_ALERT_THRESHOLD",
		"high",
	)
	threshold = normalize_threshold(threshold_input)

	latest_payload_raw = load_json(Path(args.latest_json))
	if not isinstance(latest_payload_raw, dict):
		raise AlertMessageError("latest.json must be a JSON object")
	latest_payload = latest_payload_raw

	decision = extract_alert_decision(latest_payload, threshold)
	run_at_local = parse_run_at(str(latest_payload.get("run_at", "")), args.timezone)
	notice_day = run_at_local.strftime("%Y-%m-%d")
	notice_kind = choose_notice_kind(decision)
	summary = latest_payload.get("summary") if isinstance(latest_payload.get("summary"), dict) else {}
	notification_key = build_notification_key(notice_day, notice_kind, decision, summary)

	message_state_path = Path(args.message_state_file)
	message_state = load_message_state(message_state_path)
	last_notification_key = str(message_state.get("last_notification_key", "")).strip()
	if not args.force and notification_key == last_notification_key:
		print(
			json.dumps(
				{
					"status": "duplicate_skipped",
					"notice_day": notice_day,
					"notice_kind": notice_kind,
					"highest_risk": decision.highest_risk,
					"threshold": decision.threshold,
					"notification_key": notification_key,
					"last_feedback_id": message_state.get("last_feedback_id"),
				},
				ensure_ascii=False,
				indent=2,
			),
		)
		return 0

	feedback_message = build_feedback_message(
		latest_payload=latest_payload,
		decision=decision,
		notice_kind=notice_kind,
		run_at_local=run_at_local,
		max_target_details=max(1, args.max_target_details),
	)

	if args.dry_run:
		category, priority, source = resolve_feedback_classification(
			notice_kind=notice_kind,
			highest_risk=decision.highest_risk,
		)
		print(
			json.dumps(
				{
					"status": "dry_run",
					"notice_day": notice_day,
					"notice_kind": notice_kind,
					"highest_risk": decision.highest_risk,
					"threshold": decision.threshold,
					"notification_key": notification_key,
					"classification": {
						"category": category,
						"priority": priority,
						"source": source,
					},
					"message": feedback_message,
				},
				ensure_ascii=False,
				indent=2,
			),
		)
		return 0

	config = build_config(env, timeout_seconds=args.timeout_seconds)
	opener = request.build_opener(request.HTTPCookieProcessor())
	login_admin(opener, config)
	category, priority, source = resolve_feedback_classification(
		notice_kind=notice_kind,
		highest_risk=decision.highest_risk,
	)
	created_feedback = create_admin_feedback(
		opener,
		config,
		feedback_message,
		category,
		priority,
		source,
	)
	created_id = int(created_feedback.get("id") or 0)
	if created_id <= 0:
		raise AlertMessageError("Create admin feedback succeeded but id is missing")

	closed_previous_ids: list[int] = []
	if not args.keep_previous_system_messages:
		closed_previous_ids = close_previous_system_messages(opener, config, created_id)

	now_utc = datetime.now(timezone.utc).isoformat()
	message_state.update(
		{
			"updated_at": now_utc,
			"last_notification_key": notification_key,
			"last_notice_day": notice_day,
			"last_notice_kind": notice_kind,
			"last_highest_risk": decision.highest_risk,
			"last_threshold": decision.threshold,
			"last_fingerprint": decision.fingerprint,
			"last_feedback_id": created_id,
			"last_report_path": latest_payload.get("report_path"),
			"last_run_at": latest_payload.get("run_at"),
			"last_closed_previous_feedback_ids": closed_previous_ids,
		},
	)
	save_message_state(message_state_path, message_state)

	print(
		json.dumps(
			{
				"status": "published",
				"notice_day": notice_day,
				"notice_kind": notice_kind,
				"decision": {
					"highest_risk": decision.highest_risk,
					"threshold": decision.threshold,
					"fingerprint": decision.fingerprint,
				},
				"feedback": {
					"id": created_id,
					"user_id": created_feedback.get("user_id"),
					"category": created_feedback.get("category"),
					"priority": created_feedback.get("priority"),
					"source": created_feedback.get("source"),
					"resolved_at": created_feedback.get("resolved_at"),
				},
				"closed_previous_feedback_ids": closed_previous_ids,
				"state_file": str(message_state_path),
			},
			ensure_ascii=False,
			indent=2,
		),
	)
	return 0


if __name__ == "__main__":
	try:
		raise SystemExit(main())
	except AlertMessageError as exc:
		print(str(exc), file=sys.stderr)
		raise SystemExit(1)
